
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'DESKTOPFooterPC': typeof import("../components/DESKTOP/FooterPC.vue")['default']
    'DESKTOPHeroFormPC': typeof import("../components/DESKTOP/HeroFormPC.vue")['default']
    'DESKTOPHeroPC': typeof import("../components/DESKTOP/HeroPC.vue")['default']
    'DESKTOPNavBarPC': typeof import("../components/DESKTOP/NavBarPC.vue")['default']
    'DESKTOPRatingsPC': typeof import("../components/DESKTOP/RatingsPC.vue")['default']
    'DESKTOPSubNavBarPC': typeof import("../components/DESKTOP/SubNavBarPC.vue")['default']
    'DESKTOPTestimonialsPC': typeof import("../components/DESKTOP/TestimonialsPC.vue")['default']
    'MOBILEFooterMOB': typeof import("../components/MOBILE/FooterMOB.vue")['default']
    'MOBILEHeroFormMOB': typeof import("../components/MOBILE/HeroFormMOB.vue")['default']
    'MOBILEHeroMOB': typeof import("../components/MOBILE/HeroMOB.vue")['default']
    'MOBILENavBarMOB': typeof import("../components/MOBILE/NavBarMOB.vue")['default']
    'MOBILERatingsMOB': typeof import("../components/MOBILE/RatingsMOB.vue")['default']
    'MOBILETestimonialsMOB': typeof import("../components/MOBILE/TestimonialsMOB.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'CalendlyInlineWidget': typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyInlineWidget.vue")['default']
    'CalendlyPopupButton': typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupButton.vue")['default']
    'CalendlyPopupWidget': typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupWidget.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyDESKTOPFooterPC': typeof import("../components/DESKTOP/FooterPC.vue")['default']
    'LazyDESKTOPHeroFormPC': typeof import("../components/DESKTOP/HeroFormPC.vue")['default']
    'LazyDESKTOPHeroPC': typeof import("../components/DESKTOP/HeroPC.vue")['default']
    'LazyDESKTOPNavBarPC': typeof import("../components/DESKTOP/NavBarPC.vue")['default']
    'LazyDESKTOPRatingsPC': typeof import("../components/DESKTOP/RatingsPC.vue")['default']
    'LazyDESKTOPSubNavBarPC': typeof import("../components/DESKTOP/SubNavBarPC.vue")['default']
    'LazyDESKTOPTestimonialsPC': typeof import("../components/DESKTOP/TestimonialsPC.vue")['default']
    'LazyMOBILEFooterMOB': typeof import("../components/MOBILE/FooterMOB.vue")['default']
    'LazyMOBILEHeroFormMOB': typeof import("../components/MOBILE/HeroFormMOB.vue")['default']
    'LazyMOBILEHeroMOB': typeof import("../components/MOBILE/HeroMOB.vue")['default']
    'LazyMOBILENavBarMOB': typeof import("../components/MOBILE/NavBarMOB.vue")['default']
    'LazyMOBILERatingsMOB': typeof import("../components/MOBILE/RatingsMOB.vue")['default']
    'LazyMOBILETestimonialsMOB': typeof import("../components/MOBILE/TestimonialsMOB.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyCalendlyInlineWidget': typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyInlineWidget.vue")['default']
    'LazyCalendlyPopupButton': typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupButton.vue")['default']
    'LazyCalendlyPopupWidget': typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupWidget.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const DESKTOPFooterPC: typeof import("../components/DESKTOP/FooterPC.vue")['default']
export const DESKTOPHeroFormPC: typeof import("../components/DESKTOP/HeroFormPC.vue")['default']
export const DESKTOPHeroPC: typeof import("../components/DESKTOP/HeroPC.vue")['default']
export const DESKTOPNavBarPC: typeof import("../components/DESKTOP/NavBarPC.vue")['default']
export const DESKTOPRatingsPC: typeof import("../components/DESKTOP/RatingsPC.vue")['default']
export const DESKTOPSubNavBarPC: typeof import("../components/DESKTOP/SubNavBarPC.vue")['default']
export const DESKTOPTestimonialsPC: typeof import("../components/DESKTOP/TestimonialsPC.vue")['default']
export const MOBILEFooterMOB: typeof import("../components/MOBILE/FooterMOB.vue")['default']
export const MOBILEHeroFormMOB: typeof import("../components/MOBILE/HeroFormMOB.vue")['default']
export const MOBILEHeroMOB: typeof import("../components/MOBILE/HeroMOB.vue")['default']
export const MOBILENavBarMOB: typeof import("../components/MOBILE/NavBarMOB.vue")['default']
export const MOBILERatingsMOB: typeof import("../components/MOBILE/RatingsMOB.vue")['default']
export const MOBILETestimonialsMOB: typeof import("../components/MOBILE/TestimonialsMOB.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const CalendlyInlineWidget: typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyInlineWidget.vue")['default']
export const CalendlyPopupButton: typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupButton.vue")['default']
export const CalendlyPopupWidget: typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupWidget.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyDESKTOPFooterPC: typeof import("../components/DESKTOP/FooterPC.vue")['default']
export const LazyDESKTOPHeroFormPC: typeof import("../components/DESKTOP/HeroFormPC.vue")['default']
export const LazyDESKTOPHeroPC: typeof import("../components/DESKTOP/HeroPC.vue")['default']
export const LazyDESKTOPNavBarPC: typeof import("../components/DESKTOP/NavBarPC.vue")['default']
export const LazyDESKTOPRatingsPC: typeof import("../components/DESKTOP/RatingsPC.vue")['default']
export const LazyDESKTOPSubNavBarPC: typeof import("../components/DESKTOP/SubNavBarPC.vue")['default']
export const LazyDESKTOPTestimonialsPC: typeof import("../components/DESKTOP/TestimonialsPC.vue")['default']
export const LazyMOBILEFooterMOB: typeof import("../components/MOBILE/FooterMOB.vue")['default']
export const LazyMOBILEHeroFormMOB: typeof import("../components/MOBILE/HeroFormMOB.vue")['default']
export const LazyMOBILEHeroMOB: typeof import("../components/MOBILE/HeroMOB.vue")['default']
export const LazyMOBILENavBarMOB: typeof import("../components/MOBILE/NavBarMOB.vue")['default']
export const LazyMOBILERatingsMOB: typeof import("../components/MOBILE/RatingsMOB.vue")['default']
export const LazyMOBILETestimonialsMOB: typeof import("../components/MOBILE/TestimonialsMOB.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyCalendlyInlineWidget: typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyInlineWidget.vue")['default']
export const LazyCalendlyPopupButton: typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupButton.vue")['default']
export const LazyCalendlyPopupWidget: typeof import("../node_modules/nuxt-calendly/dist/runtime/components/CalendlyPopupWidget.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
