// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/14/2024, 7:15:11 AM
const configMerger = require("/Users/rizwin/Desktop/calico-designs/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/rizwin/Desktop/calico-designs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/plugins/**/*.{js,ts,mjs}","/Users/rizwin/Desktop/calico-designs/composables/**/*.{js,ts,mjs}","/Users/rizwin/Desktop/calico-designs/utils/**/*.{js,ts,mjs}","/Users/rizwin/Desktop/calico-designs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwin/Desktop/calico-designs/app.config.{js,ts,mjs}"] } }));

module.exports = config
